An Industry Insider Drives an Open Alternative to Big Tech’s A.I.
NY Times · by Steve Lohr · October 19, 2023
The nonprofit Allen Institute for AI, led by a respected computer scientist who sold his company to Apple, is trying to democratize cutting-edge research.


Ali Farhadi, the chief executive of the Allen Institute for AI in Seattle, is making a bold move in artificial intelligence research.Credit...Chona Kasinger for The New York Times

By

Steve Lohr has written about technology research and open-source software for two decades.

Oct. 19, 2023
Ali Farhadi is no tech rebel.

The 42-year-old computer scientist is a highly respected researcher, a professor at the University of Washington and the founder of a start-up that was acquired by Apple, where he worked until four months ago.

But Mr. Farhadi, who in July became chief executive of the Allen Institute for AI, is calling for “radical openness” to democratize research and development in a new wave of artificial intelligence that many believe is the most important technology advance in decades.

The Allen Institute has begun an ambitious initiative to build a freely available A.I. alternative to tech giants like Google and start-ups like OpenAI. In an industry process called open source, other researchers will be allowed to scrutinize and use this new system and the data fed into it.

The stance adopted by the Allen Institute, an influential nonprofit research center in Seattle, puts it squarely on one side of a fierce debate over how open or closed new A.I. should be. Would opening up so-called generative A.I., which powers chatbots like OpenAI’s ChatGPT and Google’s Bard, lead to more innovation and opportunity? Or would it open a Pandora’s box of digital harm?

Definitions of what “open” means in the context of the generative A.I. vary. Traditionally, software projects have opened up the underlying “source” code for programs. Anyone can then look at the code, spot bugs and make suggestions. There are rules governing whether changes get made.

That is how popular open-source projects behind the widely used Linux operating system, the Apache web server and the Firefox browser operate.

Thank you for your patience while we verify access.

Already a subscriber? Log in.

Want all of The Times? Subscribe.

NY Times · by Steve Lohr · October 19, 2023
SUMMARY
HIGHLIGHTS
Loading...